scrapeEvent();

function scrapeEvent() {
	var raw_time = document.getElementsByClassName("_publicProdFeedInfo__timeRowTitle _5xhk")[0].getAttribute("content");
	var raw_location_name = document.querySelectorAll('[data-testid="event-permalink-location"]')[0].innerHTML;
	var raw_location_address = document.getElementsByClassName("_5xhp fsm fwn fcg")[1].innerHTML;
	var event_name = document.querySelectorAll('[data-testid=event-permalink-event-name')[0].innerHTML;

	var raw_details = document.getElementsByClassName("_4n-j _3cht fsl")[0].innerText;
	if (raw_details.lastIndexOf("See More") > 0) {
		raw_details = raw_details.substr(0, raw_details.lastIndexOf("See More")) + raw_details.substr(raw_details.lastIndexOf("See More") + 8);
	} else {
		raw_details += "\n\n";
	}

	var url = "http://www.google.com/calendar/event?action=TEMPLATE"

	raw_time = raw_time.replace(" to ", "/");
	var start_time = raw_time.substr(0, raw_time.indexOf("/"));
	var end_time = raw_time.substr(raw_time.indexOf("/") + 1);
	start_time = formatTime(new Date(start_time));
	end_time = formatTime(new Date(end_time));

	url += "&dates=" + start_time + "\/" + end_time;
	url += "&details=" + encodeURI(raw_details + window.location.href + "\n\nGenerated by Facebook Event Puller");
	url += "&text=" + encodeURI(event_name);
	url += "&location=" + encodeURI(raw_location_name + ", " + raw_location_address);

	window.open(url);
}
function formatTime(d) {
	var time_string = "";
	time_string += d.getYear() + 1900;
	time_string += formatDM(d.getUTCMonth()+1);
	time_string += formatDM(d.getUTCDate());
	time_string += "T";
	time_string += formatDM(d.getUTCHours());
	time_string += formatDM(d.getUTCMinutes());
	time_string += formatDM(d.getUTCSeconds());
	time_string += "Z";
	return time_string;
}

function formatDM(n){
    return n > 9 ? "" + n: "0" + n;
}
